### ISSUE TITLE
用eclipse倒入后编译安装正常执行报错

### ISSUE THREAD

**Issue by micookie** [likebamboo/ImageChooser#7]
E/AndroidRuntime(32056): java.lang.NoClassDefFoundError: Failed resolution of:com/nostra13/universalimageloader/core/ImageLoaderConfiguration$Builder;
    E/AndroidRuntime(32056): 	at com.likebamboo.imagechooser.ICApplication.onCreate(ICApplication.java:32)
    E/AndroidRuntime(32056): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
    E/AndroidRuntime(32056): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4621)

在项目根目录下的.clsaapath文件中
    <classpathentry kind="con" path="com.android.ide.eclipse.adt.LIBRARIES">
改为
    <classpathentry exported="true" kind="con" path="com.android.ide.eclipse.adt.LIBRARIES">

**Comment by micookie** [comment]
在项目根目录下的.clsaapath文件中
	\<classpathentry kind="con" path="com.android.ide.eclipse.adt.LIBRARIES">
改为
	\<classpathentry  exported="true" kind="con" path="com.android.ide.eclipse.adt.LIBRARIES">

**Comment by likebamboo** [comment]
@micookie 多谢提醒，之后我会将这个项目改成基于Android Studio项目结构的形式
